// permission groups shared by Navbar.vue and SideBar.vue's nav-item visibility checks
export const APP_PERMISSIONS = ['APP_EDIT', 'APP_USE'];
export const PIPELINE = ['PIPELINE', 'PIPELINE_RUN'];
export const DASHBOARD_PERMISSIONS = ['DASHBOARD_EDIT', 'DASHBOARD_EDIT_ANY',
    'DASHBOARD_VIEW', 'DASHBOARD_VIEW_ANY'];
export const DATA_SOURCE_PERMISSIONS = ['DATA_SOURCE_EDIT', 'DATA_SOURCE_LIST',
    'DATA_SOURCE_VIEW', 'DATA_SOURCE_EDIT_ANY', 'DATA_SOURCE_VIEW_ANY',
    'DATA_SOURCE_USE', 'DATA_SOURCE_USE_ANY'];
export const JOB_PERMISSIONS = ['JOB_EDIT_ANY', 'RUN_WORKFLOW_API', 'JOB_VIEW_ANY'];
export const WORKFLOW_PERMISSIONS = ['WORKFLOW_EDIT', 'WORKFLOW_LIST',
    'WORKFLOW_VIEW', 'WORKFLOW_EDIT_ANY', 'WORKFLOW_VIEW_ANY',
    'WORKFLOW_EXECUTE', 'WORKFLOW_EXECUTE_ANY'];
